Перенос серверной логики определения webview из коров + добавление кук
core-ds/bridge-to-native pull request #29
Opened 2024-11-01 08:27 UTC by andreitakarski

- В b2n перенесено все в папку client;
- Перенесена вся логика из папки extract-alfa-mobile-webview-params в корах в папку server;
- Добавлена кука с параметрами вебвью
- Добавлена проверка куки при определении вебвью окружения

2024-11-12 13:14 UTC, puptup submitted a review, later dismissed

2024-11-14 10:31 UTC, evgen-kent submitted a review, later dismissed

2024-11-14 15:04 UTC, vahrammer requested changes
Привет.
* Нужно добавить `README.md` с инструкциями для партнёров;
* Нужно всё упростить на сервере:
    *  Если кука уже есть – значит это вебвью окружение, информация об АМ уже там. Можно ничего не делать.
    * Если куки нет:
        * чекнуть, вебвью ли?
        * для вебвью записать в куку инфу о нативном приложении.

Всякие особенности нашего веб-приложения (Capsule, Voskhod) здесь не нужны.

Наверно, было бы круто, на клиенте добавить утилитку, которая сама будет парсить куку, создавать экземпляр `b2native` и возвращть его.

2024-12-03 07:37 UTC, vahrammer requested changes
Привет.
Глянь ещё комментики, пожалуйста 😇

Всё не успел посмотреть, хочу в течение дня досмотреть...

2024-12-03 07:37 UTC, vahrammer commented on README.md
> +При отправке запроса сервер определяет что запрос был сделан из вебвью (по `User-Agent` или ранее установленной `cookie`), извлекает параметры запроса, создает cookie с этими данными и отправляет кли
**suggestion:** Стоит расписать подробнее.

```suggestion
## Серверные утилиты

1. При открытии веб-ресурса в вебвью, нативное приложение добавляет к первому запросу заголовки, по которым можно определить вебвью окружение. Это актуально, если ваше веб-приложение работает по-разному в вебвью и обычном окружении (например, нужно отдать разные бандлы).

1. Также в query-параметрах и заголовках нативное приложение присылает информацию о себе, которую удобно сохранить в cookie, чтобы далее использовать на клиенте.

b2native предоставляет несколько утилиток для Node.js серверов, которые решают эти небольшие задачи.
```

2024-12-03 07:37 UTC, vahrammer commented on README.md
> +const { isWebviewEnvironment, extractNativeParams, setNativeParamsCookie } = require('@alfalab/bridge-to-native');
**suggestion:** Упростить и оставить только две функции – `isWebviewEnvironment` и `handleNativeParams`.

На мой взгляд `handleNativeParams` должна парсить запрос, вытаскивая всю необходимую информацию, и ставить куку (или не делать этого, если кука уже есть). А также возвращать объект с информацией на случай, если эта инфа кому-то нужна будет на сервере.

Хотелось бы избежать необходимости пользователям библиотеки самим устанавливать куку. Предлагаю, чтобы `handleNativeParams` принимала один аргумент – функцию для установки заголовка (учитывая разные веб-сервера). Возможно, такая сигнатура будет удобна:

```typescript
type HandleNativeParams = {
  	(setHeader: (headerKey: string, haderValue: string) => void): NativeParams;
}
```

2024-12-03 21:20 UTC, vahrammer commented on src/server/types.ts
> +export type EmptyWebviewParams = {
**polish:** Кажется, больше нигде не используется.

2024-12-03 21:20 UTC, vahrammer commented on src/server/types.ts
> +export type WebviewParams = NativeParamsType & {
**thought:** Кажется, не нужны эти `isWebview` и `withoutLayout`.

2024-12-18 08:52 UTC, sashabull66 approved these changes

2024-12-19 14:28 UTC, vahrammer requested changes
Привет.

Предлагаю следующие изменения к этому ПР → https://github.com/core-ds/bridge-to-native/tree/feat/NEWCLICKUI-3942_suggestions (можно зачерипикать коммиты, если нет замечаний).

Там 👆 пока только к серверной части изменения, по фронту есть вопросы по существующей реализации. Надо отдельно разбираться.

### Мотивация по изменениям.

* Мы должны эту либу делать универсальной – подходящей для любого партнера, не затаскивая сюда сущности из нашего веб-приложения (что за `blankPagePath`?);
* Мы должны сделать её как можно более легкой в использовании, максимально инкапсулируя детали реализиции вебвью модуля нативного приложения (зачем в `index` экспорт внутренних методов?).

### Что сделано

В `server` теперь только две функции в `index`:

* `isWebviewEnvironment`– чтобы партнер мог узнать, пришел запрос из вебвью нашего нативного приложения или нет;
* `storeNativeParamsForClientIfWebview` – чтобы партнёр мог просто вызвать эту функцию, и за него все само распарсилось и записалось в куку.

Все, о чем он должен знать – это интерфейс этих двух функций.

### Что ещё нужно сделать

* Автоматически читать куку при инициализации b2native на клиенте (убрать `nativeParams` вообще);
* Убрать все специфичные для нашего веб-приложения фичи (типа blankPage, handleRedirect и пр.).

2024-12-24 10:07 UTC, closed without merging